<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('staff',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('department_id')->nullable()->constrained()->nullOnDelete();$t->string('employee_code',50)->nullable();$t->string('name');$t->string('phone',40)->nullable();$t->string('status',20)->default('active')->index();$t->timestamps();$t->unique(['hotel_id','employee_code']);});
Schema::create('staff_shifts',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('staff_id')->constrained()->cascadeOnDelete();$t->timestamp('starts_at');$t->timestamp('ends_at');$t->string('status',20)->default('scheduled');$t->timestamps();$t->index(['hotel_id','starts_at','ends_at']);});
Schema::create('service_requests',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('room_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('guest_session_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('service_id')->constrained()->restrictOnDelete();$t->foreignId('department_id')->constrained()->restrictOnDelete();$t->string('request_number',40)->unique();$t->string('priority',20)->default('normal')->index();$t->string('status',30)->default('PENDING')->index();$t->text('guest_note')->nullable();$t->timestamp('response_due_at')->nullable()->index();$t->timestamp('completion_due_at')->nullable()->index();$t->timestamp('accepted_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();$t->index(['hotel_id','status','created_at']);$t->index(['hotel_id','department_id','status']);});
Schema::create('service_assignments',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('service_request_id')->constrained()->cascadeOnDelete();$t->foreignId('staff_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('assigned_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('assigned_at');$t->timestamp('unassigned_at')->nullable();$t->timestamps();$t->index(['hotel_id','staff_id','assigned_at']);});
Schema::create('service_request_status_history',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('service_request_id')->constrained()->cascadeOnDelete();$t->foreignId('changed_by')->nullable()->constrained('users')->nullOnDelete();$t->string('from_status',30)->nullable();$t->string('to_status',30);$t->text('note')->nullable();$t->timestamp('created_at')->index();$t->index(['hotel_id','service_request_id','created_at']);});
}public function down():void{foreach(['service_request_status_history','service_assignments','service_requests','staff_shifts','staff'] as $x)Schema::dropIfExists($x);}};
