<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('hotels',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->string('email')->nullable();$t->string('phone',40)->nullable();$t->string('timezone',80)->default('UTC');$t->string('status',30)->default('active')->index();$t->string('address_line1')->nullable();$t->string('address_line2')->nullable();$t->string('city',100)->nullable();$t->string('state',100)->nullable();$t->string('country',100)->nullable();$t->string('postal_code',30)->nullable();$t->timestamps();$t->softDeletes();});
Schema::create('hotel_users',function(Blueprint $t){$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->boolean('is_owner')->default(false);$t->string('status',20)->default('active')->index();$t->timestamps();$t->primary(['hotel_id','user_id']);});
Schema::create('permissions',function(Blueprint $t){$t->id();$t->string('name')->unique();$t->string('label');});
Schema::create('roles',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->nullable()->constrained()->cascadeOnDelete();$t->string('name');$t->string('label');$t->string('scope',20)->default('hotel');$t->timestamps();$t->unique(['hotel_id','name']);});
Schema::create('role_permissions',function(Blueprint $t){$t->foreignId('role_id')->constrained()->cascadeOnDelete();$t->foreignId('permission_id')->constrained()->cascadeOnDelete();$t->timestamps();$t->primary(['role_id','permission_id']);});
Schema::create('user_roles',function(Blueprint $t){$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('role_id')->constrained()->cascadeOnDelete();$t->foreignId('hotel_id')->nullable()->constrained()->cascadeOnDelete();$t->timestamps();$t->unique(['user_id','role_id','hotel_id'],'user_role_hotel_unique');});
Schema::create('hotel_brandings',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->unique()->constrained()->cascadeOnDelete();$t->string('logo_path')->nullable();$t->string('cover_image_path')->nullable();$t->string('primary_color',20)->default('#172554');$t->string('accent_color',20)->default('#C8A96A');$t->text('welcome_message')->nullable();$t->string('font_family',80)->nullable();$t->timestamps();});
}public function down():void{Schema::dropIfExists('hotel_brandings');Schema::dropIfExists('user_roles');Schema::dropIfExists('role_permissions');Schema::dropIfExists('roles');Schema::dropIfExists('permissions');Schema::dropIfExists('hotel_users');Schema::dropIfExists('hotels');}};
