<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('floors',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('name');$t->integer('number')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->timestamps();$t->index(['hotel_id','sort_order']);});
Schema::create('room_types',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('name');$t->text('description')->nullable();$t->unsignedSmallInteger('capacity')->default(2);$t->decimal('base_rate',12,2)->default(0);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['hotel_id','name']);});
Schema::create('rooms',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('floor_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('room_type_id')->constrained()->restrictOnDelete();$t->string('number',30);$t->string('name')->nullable();$t->string('status',30)->default('available')->index();$t->text('notes')->nullable();$t->boolean('is_active')->default(true)->index();$t->timestamps();$t->softDeletes();$t->unique(['hotel_id','number'],'rooms_hotel_number_unique');$t->index(['hotel_id','status','is_active']);});
Schema::create('qr_codes',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('public_token',64)->unique();$t->morphs('qrable');$t->string('label')->nullable();$t->boolean('is_active')->default(true)->index();$t->timestamp('last_scanned_at')->nullable();$t->timestamps();$t->index(['hotel_id','is_active']);});
Schema::create('qr_scans',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('qr_code_id')->constrained()->cascadeOnDelete();$t->foreignId('room_id')->nullable()->constrained()->nullOnDelete();$t->uuid('anonymous_session_id')->nullable()->index();$t->string('ip_hash',64)->nullable();$t->text('user_agent')->nullable();$t->text('referrer')->nullable();$t->timestamp('scanned_at')->index();$t->timestamps();$t->index(['hotel_id','qr_code_id','scanned_at']);});
Schema::create('guest_sessions',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('room_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('qr_code_id')->constrained()->cascadeOnDelete();$t->string('public_id',64)->unique();$t->string('status',20)->default('active')->index();$t->string('browser_session_hash',64)->nullable()->index();$t->timestamp('expires_at')->index();$t->timestamp('last_seen_at')->nullable();$t->timestamps();$t->index(['hotel_id','room_id','status']);});
Schema::create('departments',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('code',50);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['hotel_id','code']);});
Schema::create('service_categories',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('slug');$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['hotel_id','slug']);});
Schema::create('services',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('service_category_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('department_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('slug');$t->text('description')->nullable();$t->unsignedSmallInteger('target_response_minutes')->default(10);$t->unsignedSmallInteger('target_completion_minutes')->default(20);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['hotel_id','slug']);$t->index(['hotel_id','department_id','is_active']);});
}public function down():void{foreach(['services','service_categories','departments','guest_sessions','qr_scans','qr_codes','rooms','room_types','floors'] as $x)Schema::dropIfExists($x);}};
