<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('hotel_galleries',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('category',50)->nullable();$t->string('path');$t->string('alt_text')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_cover')->default(false);$t->timestamps();$t->index(['hotel_id','sort_order']);});
Schema::create('facilities',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('name');$t->text('description')->nullable();$t->string('location')->nullable();$t->string('hours')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('hotel_policies',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('content');$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('local_recommendations',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('category',50);$t->string('name');$t->text('description')->nullable();$t->string('address')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('announcements',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('body');$t->string('priority',20)->default('normal');$t->string('audience',30)->default('all');$t->timestamp('start_at')->nullable()->index();$t->timestamp('expires_at')->nullable()->index();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('offers',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->decimal('price',12,2)->nullable();$t->timestamp('start_at')->nullable();$t->timestamp('expires_at')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('conversations',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('room_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('guest_session_id')->nullable()->constrained()->nullOnDelete();$t->string('status',20)->default('open')->index();$t->timestamp('last_message_at')->nullable()->index();$t->timestamps();$t->index(['hotel_id','status','last_message_at']);});
Schema::create('messages',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('conversation_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('guest_session_id')->nullable()->constrained()->nullOnDelete();$t->string('sender_type',20);$t->text('body');$t->timestamp('read_at')->nullable();$t->timestamps();$t->index(['hotel_id','conversation_id','created_at']);});
Schema::create('feedback',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('room_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('guest_session_id')->nullable()->constrained()->nullOnDelete();$t->string('subject_type')->nullable();$t->unsignedBigInteger('subject_id')->nullable();$t->string('rating',30);$t->text('comment')->nullable();$t->timestamps();$t->index(['hotel_id','rating','created_at']);});
Schema::create('reviews',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('guest_session_id')->nullable()->constrained()->nullOnDelete();$t->unsignedTinyInteger('score');$t->text('comment')->nullable();$t->boolean('is_published')->default(false);$t->timestamps();});
Schema::create('notifications',function(Blueprint $t){$t->uuid('id')->primary();$t->string('type');$t->morphs('notifiable');$t->text('data');$t->timestamp('read_at')->nullable();$t->timestamps();});
Schema::create('analytics_events',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('guest_session_id')->nullable()->constrained()->nullOnDelete();$t->string('event_name')->index();$t->string('entity_type')->nullable();$t->unsignedBigInteger('entity_id')->nullable();$t->json('properties')->nullable();$t->timestamp('created_at')->index();$t->index(['hotel_id','event_name','created_at']);});
Schema::create('system_settings',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->nullable()->constrained()->cascadeOnDelete();$t->string('key');$t->json('value')->nullable();$t->boolean('is_secret')->default(false);$t->timestamps();$t->unique(['hotel_id','key']);});
}public function down():void{foreach(['system_settings','analytics_events','notifications','reviews','feedback','messages','conversations','offers','announcements','local_recommendations','hotel_policies','facilities','hotel_galleries'] as $x)Schema::dropIfExists($x);}};
