<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('restaurants',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->string('name');$t->text('description')->nullable();$t->string('image_path')->nullable();$t->decimal('tax_rate',5,2)->default(0);$t->string('currency',3)->default('INR');$t->time('opens_at')->nullable();$t->time('closes_at')->nullable();$t->boolean('is_active')->default(true)->index();$t->timestamps();$t->index(['hotel_id','is_active']);});
Schema::create('menu_categories',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('restaurant_id')->constrained()->cascadeOnDelete();$t->string('name');$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['hotel_id','restaurant_id','sort_order']);});
Schema::create('menu_items',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('restaurant_id')->constrained()->cascadeOnDelete();$t->foreignId('menu_category_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->text('description')->nullable();$t->decimal('price',12,2);$t->string('image_path')->nullable();$t->unsignedSmallInteger('preparation_minutes')->default(20);$t->json('dietary_info')->nullable();$t->json('allergens')->nullable();$t->boolean('is_available')->default(true)->index();$t->timestamps();$t->index(['hotel_id','restaurant_id','is_available']);});
Schema::create('menu_modifiers',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('menu_item_id')->constrained()->cascadeOnDelete();$t->string('name');$t->decimal('price_delta',12,2)->default(0);$t->boolean('is_available')->default(true);$t->timestamps();$t->index(['hotel_id','menu_item_id','is_available']);});
Schema::create('orders',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('room_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('guest_session_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('restaurant_id')->constrained()->restrictOnDelete();$t->string('order_number',40)->unique();$t->string('idempotency_key',80);$t->string('status',30)->default('PENDING')->index();$t->decimal('subtotal',12,2);$t->decimal('tax',12,2)->default(0);$t->decimal('discount',12,2)->default(0);$t->decimal('total',12,2);$t->string('currency',3)->default('INR');$t->text('special_instructions')->nullable();$t->timestamp('accepted_at')->nullable();$t->timestamp('ready_at')->nullable();$t->timestamp('delivered_at')->nullable();$t->timestamps();$t->unique(['guest_session_id','idempotency_key'],'orders_guest_idempotency_unique');$t->index(['hotel_id','status','created_at']);});
Schema::create('order_items',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('menu_item_id')->nullable()->constrained()->nullOnDelete();$t->string('item_name');$t->decimal('unit_price',12,2);$t->unsignedSmallInteger('quantity');$t->decimal('line_total',12,2);$t->json('modifier_snapshot')->nullable();$t->text('special_instructions')->nullable();$t->timestamps();$t->index(['hotel_id','order_id']);});
Schema::create('order_status_history',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('changed_by')->nullable()->constrained('users')->nullOnDelete();$t->string('from_status',30)->nullable();$t->string('to_status',30);$t->text('note')->nullable();$t->timestamp('created_at')->index();$t->index(['hotel_id','order_id','created_at']);});
Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('hotel_id')->constrained()->cascadeOnDelete();$t->foreignId('order_id')->nullable()->constrained()->nullOnDelete();$t->string('provider',50)->nullable();$t->string('provider_reference')->nullable()->index();$t->decimal('amount',12,2);$t->string('currency',3)->default('INR');$t->string('status',30)->default('pending')->index();$t->json('metadata')->nullable();$t->timestamps();$t->index(['hotel_id','status','created_at']);});
}public function down():void{foreach(['payments','order_status_history','order_items','orders','menu_modifiers','menu_items','menu_categories','restaurants'] as $x)Schema::dropIfExists($x);}};
